### ISSUE TITLE
No method error for Rack::Timeout

### ISSUE THREAD

**Issue by atitan** [ankane/slowpoke#16]
I'm getting this error when building production container, slowpoke 0.2.0 and master branch tested.

It seems Rack::Timeout just removed those methods from their 0.5.0 release https://github.com/heroku/rack-timeout/commit/eaba89e3acd121fe67ee5221213c5cd89bdf5229.

Downgrade Rack::Timeout to 0.4.2 solve the problem.

```
NoMethodError: undefined method `service_timeout=' for Rack::Timeout:Class
/usr/local/bundle/bundler/gems/slowpoke-2035bccce534/lib/slowpoke/railtie.rb:4:in `block in <class:Railtie>'
/usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
/usr/local/bundle/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
/app/config/environment.rb:5:in `<main>'
```

**Comment by ankane** [comment]
Hey @atitan, thanks for reporting 👍 Just pushed a new version that locks down the dependency until I can upgrade to work with rack-timeout 0.5. https://github.com/ankane/slowpoke/commit/3d42c82c054a8bb78498492d0e190063cb46cf52
